config/routes.rb
Rails.application.routes.draw do
  get 'main/bob_test'

  resources :recipes

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/recipe.rb
class Recipe < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/main_controller.rb
class MainController < ApplicationController
  def bob_test
  end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  before_action :set_recipe, only: %i[ show edit update destroy ]

  # GET /recipes or /recipes.json
  def index
    @recipes = Recipe.all
  end

  # GET /recipes/1 or /recipes/1.json
  def show
  end

  # GET /recipes/new
  def new
    @recipe = Recipe.new
  end

  # GET /recipes/1/edit
  def edit
  end

  # POST /recipes or /recipes.json
  def create
    @recipe = Recipe.new(recipe_params)

    respond_to do |format|
      if @recipe.save
        format.turbo_stream
        format.html { redirect_to recipes_url, notice: "Recipe was successfully created." }
        format.json { render :show, status: :created, location: @recipe }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @recipe.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /recipes/1 or /recipes/1.json
  def update
    respond_to do |format|
      if @recipe.update(recipe_params)
        format.html { redirect_to recipe_url(@recipe), notice: "Recipe was successfully updated." }
        format.json { render :show, status: :ok, location: @recipe }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @recipe.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /recipes/1 or /recipes/1.json
  def destroy
    @recipe.destroy

    respond_to do |format|
      format.turbo_stream { render turbo_stream: turbo_stream.remove(@recipe) }
      format.html { redirect_to recipes_url, notice: "Recipe was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_recipe
      @recipe = Recipe.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def recipe_params
      params.require(:recipe).permit(:name, :ingredients, :instructions, :image_url)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Recipe3</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
    <main class="container">
      <%= yield %>
    </main>
  </body>
</html>

app/views/main/bob_test.html.erb
<div data-controller="bob" data-action="click->bob#big_bob wheel->bob#small_bob" style="font-size: 15px;"></div>

app/views/recipes/_form.html.erb
<div class="border border-dark p-2 h-100">
  <%= form_with(model: recipe) do |form| %>
    <% if recipe.errors.any? %>
      <div style="color: red">
        <h2><%= pluralize(recipe.errors.count, "error") %> prohibited this recipe from being saved:</h2>
  
        <ul>
          <% recipe.errors.each do |error| %>
            <li><%= error.full_message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
  
    <div class="mb-3">
      <%= form.label :name, class: 'form-label' %>
      <%= form.text_field :name, class: 'form-control', required: true, maxlength: 100 %>
    </div>
  
    <div class="mb-3">
      <%= form.label :ingredients, class: 'form-label' %>
      <%= form.text_area :ingredients, class: 'form-control', rows: 4, required: true, maxlength: 5000 %>
    </div>
  
    <div class="mb-3">
      <%= form.label :instructions, class: 'form-label' %>
      <%= form.text_area :instructions, class: 'form-control', rows: 4, required: true, maxlength: 5000 %>
    </div>
  
    <div class="mb-3">
      <%= form.label :image_url, class: 'form-label' %>
      <%= form.text_field :image_url, class: 'form-control', maxlength: 200 %>
    </div>
  
    <%= form.submit class: 'btn btn-primary'%>
  <% end %>
</div>

app/views/recipes/_recipe.html.erb
<%= turbo_frame_tag recipe, class: 'col-sm-6 col-md-4 col-lg-3' do %>
  <div class="border border-dark p-2 h-100">
    <p>
      <strong>Name:</strong>
      <%= recipe.name %>
    </p>

    <p>
      <strong>Ingredients:</strong>
      <%= recipe.ingredients %>
    </p>

    <p>
      <strong>Instructions:</strong>
      <%= recipe.instructions %>
    </p>

    <p>
      <strong>Image url:</strong>
      <%= recipe.image_url %>
    </p>

    <div>
      <%= link_to "Edit", edit_recipe_path(recipe), class: 'btn btn-secondary d-inline-block' %>
      <%= button_to "Remove", recipe, method: :delete, class: 'btn btn-danger d-inline-block' %>
    </div>
  </div>
<% end -%>

app/views/recipes/create.turbo_stream.erb
<%= turbo_stream.before "new_recipe" do %>
  <%= render "recipe", recipe: @recipe %>
<% end %>
<%= turbo_stream.replace "new_recipe" do %>
  <%= turbo_frame_tag :new_recipe, class: 'col-sm-6 col-md-4 col-lg-3' do %>
    <%= render "form", recipe: Recipe.new %>
  <% end -%>
<% end %>

app/views/recipes/edit.html.erb
<h1>Editing recipe</h1>

<%= turbo_frame_tag @recipe do -%>
   <%= render "form", recipe: @recipe %>
   <br>

   <div>
     <%= link_to "Cancel", @recipe %>
   </div>
<% end -%>

app/views/recipes/index.html.erb
<main class="container">
  <p style="color: green"><%= notice %></p>
  <h1>Recipes</h1>
  <%= turbo_frame_tag :recipes, class: 'row g-2 my-3' do %>
    <% @recipes.each do |recipe| %>
      <%= render recipe %>
    <% end %>
    <%= turbo_frame_tag :new_recipe, class: 'col-sm-6 col-md-4 col-lg-3' do %>
      <%= render 'form', recipe: Recipe.new %>
    <% end -%>
  <% end -%>
</main>

app/views/recipes/new.html.erb
<h1>New recipe</h1>

<%= turbo_frame_tag :new_recipe do -%>
  <%= render "form", recipe: @recipe %>
<% end -%>

<br>

<div>
  <%= link_to "Back to recipes", recipes_path %>
</div>

app/views/recipes/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @recipe %>